DEFAULT_FPS = 30
DEFAULT_WIDTH = 1080
DEFAULT_HEIGHT = 1920
DEFAULT_BG_COLOR = "black"
DEFAULT_FADE_SEC = 0.25
DEFAULT_PREVIEW_W = 270
DEFAULT_PREVIEW_H = 480

SUPPORTED_IMG_EXTS = [".png", ".jpg", ".jpeg", ".webp"]
SUPPORTED_VIDEO_EXTS = [".mp4", ".mov", ".mkv", ".webm", ".avi", ".m4v"]
SUPPORTED_AUD_EXTS = [".wav", ".mp3", ".m4a", ".aac"]

DEFAULT_FONT_SIZE = 54
DEFAULT_OVERLAY_FONT_SIZE = 52

DEFAULT_SCALE_MODE = "contain"
SCALE_MODE_OPTIONS = ["contain", "cover"]
